### PR TITLE
Use kotlin forEach instead of java

### LINKED ISSUE #58: AndroidTimeCapsule crash on API <24
AndroidTimeCapsule use forEach method that is available only from API 24 (see https://developer.android.com/reference/java/util/HashMap#forEach(java.util.function.BiConsumer%3C?%20super%20K,%20?%20super%20V%3E) and it leads to runtime crash when trying to save state on API lower than 24:

```kotlin
fun saveState(outState: Bundle) = stateSuppliers.forEach { key, stateSupplier -> outState.putParcelable(key, stateSupplier()) }
```

cc @litun

### PR DESCRIPTION
**Pull request by Litun**
Fixes #58

### CODE REVIEW

File: mvicore-android/src/main/java/com/badoo/mvicore/android/AndroidTimeCapsule.kt [hunk 1]
```diff
@@ -14,5 +15,5 @@ class AndroidTimeCapsule(private val savedState: Bundle?) : TimeCapsule<Parcelab
         stateSuppliers[key.toString()] = stateSupplier
     }
 
-    fun saveState(outState: Bundle) = stateSuppliers.forEach { key, stateSupplier -> outState.putParcelable(key, stateSupplier()) }
+    fun saveState(outState: Bundle) = stateSuppliers.kotlinForEach { entry -> outState.putParcelable(entry.key, entry.value()) }
```
Comment (lukaville) [inline mvicore-android/src/main/java/com/badoo/mvicore/android/AndroidTimeCapsule.kt]: add tests?

File: mvicore-android/src/androidTest/java/com/badoo/mvicore/android/AndroidTimeCapsuleTest.kt [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+        val timeCapsule = AndroidTimeCapsule(null)
+        timeCapsule.register("test_key") { SimpleTestParcelable("test_value") }
+
+        val bundle = Bundle()
+        timeCapsule.saveState(bundle)
+
+        val restoredTimeCapsule = AndroidTimeCapsule(bundle)
+        val restoredState = restoredTimeCapsule.get<SimpleTestParcelable>("test_key")
+
+        assert(restoredState != null)
```
Comment (lukaville) [inline mvicore-android/src/androidTest/java/com/badoo/mvicore/android/AndroidTimeCapsuleTest.kt]: please use junit assertions
